# template
[components]
nix = { name = "omegaosx-nix" }
virtio = { name = "omegaosx-virtio" }
input = { name = "omegaosx-input" }
block = { name = "omegaosx-block" }
console = { name = "omegaosx-console" }
softirq = { name = "omegaosx-softirq" }
logger = { name = "omegaosx-logger" }
time = { name = "omegaosx-time" }
framebuffer = { name = "omegaosx-framebuffer" }
network = { name = "omegaosx-network" }
mlsdisk = { name = "omegaosx-mlsdisk" }
systree = { name = "omegaosx-systree" }
keyboard = { name = "omega-keyboard" }
pci = { name = "omega-pci" }

[whitelist]
[whitelist.nix.main]
main = true
