[package]
name = "osdk-heap-allocator"
version = "0.16.1"
edition = "2021"
description = "The default slab-based heap allocator shipped with OSDK."
license = "MPL-2.0"
repository = "https://github.com/swcstudio/omegaosx"
readme = "README.md"

[dependencies]
log = "0.4"
osxtd = { version = "0.16.1", path = "../../../osxtd" }

[lints]
workspace = true
