name: Publish OSXDK and OSXTD

on:
  workflow_dispatch:
  pull_request:
    paths:
      - VERSION
      - osxtd/**
      - osxdk/**
  push:
    branches:
      - main
    paths: 
      - VERSION

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: omegaosx/omegaosx:0.16.1-20250922
    steps:
      - uses: actions/checkout@v4

      - name: Publish OSXTD and OSXDK (dry run)
        # On pull request, set `--dry-run` to check whether they can be published
        if: github.event_name == 'pull_request'
        run: |
          ./tools/github_workflows/publish_osxdk_and_osxtd.sh --dry-run
      
      - name: Publish OSXTD and OSXDK
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          ./tools/github_workflows/publish_osxdk_and_osxtd.sh --token ${REGISTRY_TOKEN}
